### ISSUE TITLE
possible bug in win32 rthreads

### ISSUE THREAD

**Issue by zeromus** [libretro/libretro-common#24]
I'm just leaving this here for tracking, in case I drop dead or something, not that im planning on it

https://sourceforge.net/p/desmume/code/5551/
https://sourceforge.net/p/desmume/bugs/1569/

**Comment by Alcaro** [comment]
> the main problem is that a condition variable can be used to wake up a thread, but only if the thread is already waiting
> whereas a win32 event will 'wake up' a thread in advance (the event will be set in advance, so a 'waiter' wont even have to wait on it)

Oh, that one's easy. Just wake the thread, call it a spurious wakeup and let the caller deal with it.

But event seems to be wrong object to emulate a condvar, since event only has two states; emulating something broadcastable with that is irritating (you see how big your scond_wait is?). I don't trust 'volatile' either, its semantics vary too much between compilers.

Solution: Use another synchronization object. Not counting the Vista+-only ones like CONDITION_VARIABLE, the best one is the semaphore.

**Comment by zeromus** [comment]
That's an old comment. But anyway it's meant to describe why a naive implementation of condvars as events is insufficient--its a grotesque mismatch.  It isn't just that easy, or else the code would not have been hanging. The analysis which proves that's insufficient is complex but at it's root I think is due to there being no primitive in win32 threading (until the new vista+ stuff) which can achieve the atomicity requirements of pthread_cond_wait without desperate measures.

Sempahore was next on the list after we finished the exploration we undertook. It seems to have some useful attributes, but the overall problem is enormous and it isn't a magic bullet. If you can solve it with a semaphore and without an equivalent mass of supporting code, I'd like to see it. We're up to about the 5th completely different algorithm, and at least 60 man-hours in trying to crack this.

**Comment by Alcaro** [comment]
> ptwin32's gpl'd implementation

[It's BSD.](https://sourceforge.net/p/mingw-w64/code/6184/tree/trunk/mingw-w64-libraries/winpthreads/COPYING) Unless there's another pthread-win32 I'm not aware of, but let's just ignore that one.

But its condition variable has 11 members, of which 5 are semaphores and critical sections, and the mutex has another 7 members. I'm pretty sure that doesn't qualify as smaller than anything.

> I use events because I use events for everything!

pf. the others are fun!

> The way I see it, volatile just reduces the chance of compiler doing something nobody expects.

I am not aware of any thread-related issues that volatile solves, according to the C/C++ standards and according to GCC.

[A volatile access doesn't prevent torn values.](https://godbolt.org/g/UL7Xx5) [The compiler can optimize across a volatile access.](https://godbolt.org/g/rr03fu) [And the CPU is still allowed to reorder volatile accesses.](https://godbolt.org/g/W0nn0N)

MSVC offers stronger volatility guarantees, and we could rely on that during development, but since we'll need it fixed for MinGW before pushing to master, it's not gaining us much.

The only real solution (other than mutex) is InterlockedIncrement/etc. Or if we want atomics in cross-platform code, more wrappers, maybe based on [this one](https://github.com/Alcaro/Arlib/blob/master/arlib/thread/atomic.h).

I'll take a look at rewriting this thing. If it really does need that much goop, then I apologize for doubting you.

**Comment by zeromus** [comment]
That's not what i call ptwin32. That's a good reference. I'll look at it if I ever try to make my approach use more atomics, which I would like to see.  Watch out, they use pthread_self() which implies the full infrastructure of pthreads. I work around that by using the linked list to store temporary data for each thread on the stack.  I planned to put more information there, but didn't end up needing it. My code isn't fully clean yet, it could be implemented without that struct at all.

I'm not interested in a smaller solution really. This subject isn't easy. I'm only interested in a solution that works.  And like I said, I dont think we need cross-platform atomics. I don't think it's smart to try to put that in libretro-common unless there's a pressing need. The need for threading problems solved by libretro-common is higher.  

I might could support bringing the whole mingw pthread implementation into libretro-common, but I would want to investigate whether that means we can use it's condvars etc. without also using its threads.  Although that's a requirement I might also be fine with. I'd feel better about this solution than some homemade stuff.  But you might find some other platforms some day that dont have pthreads and wish you had a leaner solution.

And finally, I'm not going to debate about volatile. I didn't say it "solves" anything. It simply makes the compiler behave more like you expect it to when considering your synchronization algorithms, so algorithms with bugs are less likely to fail, even if they're incorrectly solved. This is just a fact. Go look online for other people saying they swear by volatile. 

By the way I suggest you dont waste time coding on this until our main tester investigates whether the latest build works for him.

**Comment by zeromus** [comment]
Well, looks like our tester approves.

**Comment by zeromus** [comment]
https://sourceforge.net/p/desmume/code/HEAD/tree/trunk/desmume/src/libretro-common/rthreads/rthreads.c
Looks like this is gonna be our final version. I removed the volatile stuff after all.
I'll submit a PR eventually

**Comment by zeromus** [comment]
see PR #32

**Comment by zeromus** [comment]
This has been dealt with long ago in retroarch project
