### ISSUE TITLE
vc2010 compile bugs

### ISSUE THREAD

**Issue by zeromus** [libretro/libretro-common#4]
Problems in vc2010:
- fill_pathname_expand_special and fill_pathname_abbreviate_special are missing (for retro team to solve)
- there's irrational _MSC_VER ifdefs in rthreads.h (for discussion)
- nonstandard ssize_t is used by retro_file.h (needs `compat` treatment) (for myself to create a patch)
- snprintf used by retro_dirent.c (needs `compat` treatment) (for myself to create a patch)

note: none of these are blockers for me presently, since I don't need the functions in the first bullet point and the others are easy to workaround

**Comment by Alcaro** [comment]
> fill_pathname_expand_special and fill_pathname_abbreviate_special are missing

They're in RetroArch, file_path_special.c.

Not sure if they should be removed from or added to -common, but I agree that one of them should be done. Probably add, since -common/file/config_file.c wants them.

> there's irrational _MSC_VER ifdefs in rthreads.h (for discussion)

Probably related to RetroArch building as C++ on Windows.

My guess: rthreads.c didn't include rthreads.h, so it used C++ linkage. Someone decided to use the first solution that works and smashed them in.

Should be an easy fix.

> nonstandard ssize_t is used by retro_file.h

that one should be standard. lazy standards teams.

> snprintf used by retro_dirent.c

I thought snprintf was supported by MSVC? Guess not... but should be easy to fix with something stupid, like _snprintf or sprintf_s.

**Comment by zeromus** [comment]
OK, as I thought, you can't think of any good reason for the rthreads.h stuff. I'll just fix that too.

snprintf_s isnt exactly the same as snprintf, so you have to write a special wrapper to make sure it's the same. it suggests a compat_snprintf.c which I'll put together.

While we're on the subject, there's at least a couple of different approaches to naming the compat functions
ex.
retro_strcasecmp__
strcasestr_retro__

Which do you consider most uptodate? (I like the latter, since retro_XXX looks like a libretro-common provided service and strcasestr_retro__ looks like a retro version of strcasestr)

**Comment by zeromus** [comment]
well, this is stale. we'll address this some other way again when the time comes
